name: kids_story_ai
description: Parent Flutter project that includes mobile, dashboard, and shared modules.
publish_to: none

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
